### ISSUE TITLE
 Materialization "materialization_table_clickhouse" only supports languages ['sql']; got "python"

### ISSUE THREAD

**Issue by nazfoxway** [ClickHouse/dbt-clickhouse#232] opened 2023-12-28 11:55 UTC
Please add support to python models materialization.

**Comment by genzgd** [comment] 2023-12-28 13:01
Duplicate of https://github.com/ClickHouse/dbt-clickhouse/issues/113

**Closed by genzgd** 2023-12-28 13:01 UTC
Labels: enhancement
